# Configuration for Dependabot
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Update all Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    update: "widen"
    automerged: true
    allow:
      - dependency-name: "dependabot"
        dependency-type: "all"
        updates: "major"
  # Update workflow files every day
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    update: "widen"
    automerged: false
    allow:
      - dependency-name: "dependabot"
        dependency-type: "all"
        updates: "major"